output: prefixed
debug: false

import:
  - https://raw.githubusercontent.com/Ensono/eirctl/refs/tags/0.9.17/shared/build/go/eirctl.yaml
  - https://raw.githubusercontent.com/Ensono/eirctl/refs/tags/0.9.17/shared/security/eirctl.yaml

contexts:
  bash:
    container:
      name: mirror.gcr.io/bash:5.0.18-alpine3.22

  go1xalpine:
    container:
      name: mirror.gcr.io/golang:1.26-alpine
    envfile:
      exclude:
        - GO
        - CXX
        - CGO

pipelines:
  unit:test:
    - pipeline: test:unit
      env:
        ROOT_PKG_NAME: github.com/DevLabFoundry/configmanager-plugin-awssecretsmanager

  gha:unit:test:
    - pipeline: unit:test
    - task: sonar:coverage:prep
      depends_on: unit:test

  code:coverage:
    - pipeline: unit:test
    - task: show_coverage
      depends_on: unit:test

  build:bin:
    - task: clean
    - task: go:build:plugin
      env:
        PLUGIN: awssecretsmanager
      depends_on: clean

  scan:plugins:
    - task: trivy:file:system:sbom

tasks:
  go:build:plugin:
    context: go1xalpine
    command:
      - |
        mkdir -p .deps
        unset GOTOOLCHAIN
        ldflags="-s -w -X \"main.Version=${VERSION}\" -X \"main.Revision=${REVISION}\" -extldflags -static"
        export GOPATH=/eirctl/.deps GOOS=${BUILD_GOOS} GOARCH=${BUILD_GOARCH} CGO_ENABLED=0 
        go build -mod=readonly -buildvcs=false -ldflags="$ldflags" \
        -o dist/$PLUGIN-${BUILD_GOOS}-${BUILD_GOARCH}${BUILD_SUFFIX} main.go
        echo "---"
        echo "Built: $PLUGIN-${BUILD_GOOS}-${BUILD_GOARCH}${BUILD_SUFFIX}"
    reset_context: true
    variations:
      - BUILD_GOOS: darwin
        BUILD_GOARCH: amd64
        BUILD_SUFFIX: ""
      - BUILD_GOOS: darwin
        BUILD_GOARCH: arm64
        BUILD_SUFFIX: ""
      - BUILD_GOOS: linux
        BUILD_GOARCH: amd64
        BUILD_SUFFIX: ""
      - BUILD_GOOS: linux
        BUILD_GOARCH: arm64
        BUILD_SUFFIX: ""
      - BUILD_GOOS: windows
        BUILD_GOARCH: amd64
        BUILD_SUFFIX: ".exe"
      - BUILD_GOOS: windows
        BUILD_GOARCH: arm64
        BUILD_SUFFIX: ".exe"
      - BUILD_GOOS: windows
        BUILD_GOARCH: "386"
        BUILD_SUFFIX: ".exe"
    required:
      env:
        - PLUGIN

  sonar:coverage:prep:
    context: bash
    command:
      - |
        sed -i 's|github.com/DevLabFoundry/configmanager-plugin-awssecretsmanager/||g' .coverage/out
        echo "Coverage file first 20 lines after conversion:"
        head -20 .coverage/out
        echo "Coverage file line count:"
        wc -l .coverage/out

  tag:
    description: |
      Usage `eirctl tag GIT_TAG=2111dsfsdfa REVISION=as2342432`
